const mealData={breakfast:{label:'早餐 · 稳定能量',title:'鸡蛋燕麦莓果碗',copy:'全谷物 + 优质蛋白，帮你把上午的能量拉稳。',kcal:'420',protein:'24g 蛋白质',fiber:'8g 纤维',fat:'14g 脂肪',reason:'今天优先补充蛋白质和膳食纤维，减少上午反复想吃零食。',img:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85'},lunch:{label:'午餐 · 盘子要完整',title:'香煎鸡胸藜麦盘',copy:'一半蔬菜、四分之一蛋白质、四分之一主食。',kcal:'560',protein:'42g 蛋白质',fiber:'11g 纤维',fat:'18g 脂肪',reason:'午餐把蔬菜体积做足，下午更有饱腹感，也不影响晚餐。',img:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=85'},dinner:{label:'晚餐 · 轻一点也完整',title:'豆腐蒸鱼蔬菜汤',copy:'晚餐不靠跳餐，温和地收住今天的能量。',kcal:'470',protein:'36g 蛋白质',fiber:'9g 纤维',fat:'16g 脂肪',reason:'保留蛋白质和蔬菜，减少额外酱料，睡前更舒服。',img:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85'}};
let activeSlot='breakfast';
function renderMeal(slot){activeSlot=slot;const m=mealData[slot];document.querySelector('.dish-image').style.backgroundImage=`url(${m.img})`;document.querySelector('.dish-label').textContent=m.label;document.querySelector('.meal-body h4').textContent=m.title;document.querySelector('.meal-body p').textContent=m.copy;document.querySelector('.why').textContent='营养师判断：'+m.reason;document.querySelectorAll('.macro-line span')[0].textContent=m.protein;document.querySelectorAll('.macro-line span')[1].textContent=m.fiber;document.querySelectorAll('.macro-line span')[2].textContent=m.fat;document.querySelector('.kcal').textContent=m.kcal+' kcal';document.querySelectorAll('.meal-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.slot===slot));const record=document.querySelector('.record .primary');if(record){record.textContent='记录这餐';record.classList.remove('recorded')}}
function openSheet(title,copy,action='知道了',html=false){const dialog=document.querySelector('.dialog');dialog.querySelector('h3').textContent=title;const body=dialog.querySelector('p');html?body.innerHTML=copy:body.textContent=copy;dialog.querySelector('.start').textContent=action;dialog.classList.add('open')}
function quickActions(){const expert=document.querySelector('.expert');if(!expert)return;expert.insertAdjacentHTML('afterend','<div class="quick-actions"><button data-quick="record"><b>＋</b>记录一餐</button><button data-quick="pantry"><b>⌁</b>冰箱做菜</button><button data-quick="gap"><b>◌</b>营养缺口</button><button data-quick="profile"><b>◎</b>我的档案</button></div>');const meal=document.querySelector('.meal-card');if(meal)meal.insertAdjacentHTML('afterend','<button class="ai-composer" data-quick="chat"><span class="ai-composer-mark">营</span><span><strong>告诉营养师你想吃什么</strong><span>例如：我只有鸡蛋和番茄 · 今晚想吃辣的</span></span><span class="ai-composer-arrow">›</span></button>')}
function openPantry(){openSheet('冰箱里有什么？','选择你手边的食材，AI 会优先按你的目标和口味生成一份能马上做的菜。','生成食谱',true);const p=document.querySelector('.dialog p');p.innerHTML='<div class="ingredient-chips"><button class="selected">鸡蛋</button><button class="selected">西兰花</button><button>番茄</button><button>豆腐</button><button>鸡胸肉</button><button>燕麦</button></div><div class="sheet-note">可继续添加食材 · 生成后会同步到今日计划</div>';p.querySelectorAll('.ingredient-chips button').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('selected')))}
document.addEventListener('DOMContentLoaded',()=>{quickActions();renderMeal('breakfast');const sectionTitles=document.querySelectorAll('.section-head h3');if(sectionTitles.length>1)sectionTitles[sectionTitles.length-1].textContent='AI 下一餐建议';
  document.querySelectorAll('.meal-tabs button').forEach(b=>b.addEventListener('click',()=>renderMeal(b.dataset.slot)));
  document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.quick;if(action==='record')openSheet('记录一餐','可以拍照识别、搜索菜名，或手动填写实际份量。记录后我会重新计算今天的营养缺口。','打开记录能力');if(action==='pantry')openPantry();if(action==='gap')openSheet('今日营养缺口','当前蛋白质完成 77%，纤维完成 56%。下一餐优先选择鱼、蛋、豆制品，并补一份蔬菜。','看下一餐');if(action==='profile')openSheet('我的营养档案','当前：日常健康。可切换减脂塑形、孕期营养，并补充过敏、疾病和用药信息。','编辑档案');if(action==='chat')openSheet('告诉营养师','你可以直接输入：我只有鸡蛋和番茄、今晚想吃辣的、这份外卖怎么调整。AI 会先理解你的限制，再给出下一步。','开始对话')}));
  document.querySelectorAll('.bottom button').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.bottom button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const copy=['回到今日建议，查看适合你的下一餐。','打开记录能力：拍照、搜菜名或手动填写实际份量。','打开你的健康档案，调整目标、口味和过敏项。'][i];openSheet(['今日','记录','我的'][i],copy,i===0?'回到今日':'打开能力')}));
  document.querySelector('.ask').addEventListener('click',()=>openSheet('和营养师聊聊','告诉我你现在想吃什么，或者拍下餐盘。我会先看整体搭配，再给你一条能执行的建议。','开始咨询'));
  document.querySelector('.hero-cta').addEventListener('click',()=>openSheet('为什么这样搭','这一餐把蛋白质、膳食纤维和主食放在同一张盘子里，先解决饱腹感，再减少下午的随机加餐。','理解了'));
  document.querySelectorAll('.section-head button').forEach(b=>b.addEventListener('click',()=>{const text=b.textContent;if(text.includes('详情')||text.includes('进度')||text.includes('营养环'))openSheet('今日营养信号','能量完成 71%，蛋白质完成 77%，纤维完成 56%。下一餐优先补足蛋白质和蔬菜。','继续看建议');else if(text.includes('编辑')||text.includes('目标'))openSheet('编辑营养目标','当前档案：日常健康。你可以切换到减脂或孕期模式，并调整口味偏好和过敏项。','打开档案');else if(text.includes('食谱')||text.includes('餐盘')||text.includes('换')){const next=activeSlot==='breakfast'?'lunch':activeSlot==='lunch'?'dinner':'breakfast';renderMeal(next)}}));
  document.querySelector('.record .primary').addEventListener('click',e=>{e.currentTarget.textContent='已记录 ✓';e.currentTarget.classList.add('recorded');openSheet('已记下这餐',`已记录「${mealData[activeSlot].title}」${mealData[activeSlot].kcal} kcal。接下来我会按实际摄入调整建议。`,'查看今日记录')});
  document.querySelector('.record .ghost').addEventListener('click',()=>openSheet(mealData[activeSlot].title+' · 菜谱','食材：鸡蛋、燕麦、时令蔬果。做法：先准备蛋白质，再加入全谷物和蔬菜，少油完成。','开始烹饪'));
  document.querySelector('.close').addEventListener('click',()=>document.querySelector('.dialog').classList.remove('open'));
  document.querySelector('.start').addEventListener('click',()=>{document.querySelector('.dialog p').textContent='好的，这项能力已经为你准备好了，可以继续下一步。';document.querySelector('.start').textContent='已完成'});
});
